1-js/06-advanced-functions/05-global-object/article.md
Translate **Global object** article in French.
=> Global object

1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/_js.view/source.js, 1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/solution.md, 1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/task.md, 1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/solution.md, 1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/task.md
=> Function object, NFE (Tasks)

2-ui/1-document/01-browser-environment/article.md
There is the translate of the "Browser environment, specs" article in french.
=> Translate of "Browser environment, specs" in french

2-ui/3-event-details/1-mouse-events-basics/article.md
submission of  the mouse-events-basics article translation into french
=> Mouse events basics

2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/solution.md, 2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/task.md, 2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.md, 2-ui/1-document/05-basic-dom-node-properties/2-tree-info/task.md, 2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md, 2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/task.md, 2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/solution.md, 2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/task.md, 2-ui/1-document/05-basic-dom-node-properties/article.md
=> Node properties: type, tag and contents

2-ui/4-forms-controls/3-events-change-input/article.md
_Events: change, input, cut, copy, paste_ translated in French
=> Events: change, input, cut, copy, paste

9-regular-expressions/12-regexp-backreferences/article.md
Correction : le mot "pattern" ne doit pas être traduit par "paterne" car ce sont deux mots différents (et ce dernier ne peut pas prendre le sens du premier) ; on doit donc laisser "pattern" tel quel
=> Paterne -> Pattern

1-js/04-object-basics/07-optional-chaining/article.md
Did the best I could with `warn header` sections but difficult as my editor 'Typora' does not handle them right, so I tried to balance back-tick clusters manually for the source markdown.
Also I haven't altered the initial `[recent browser="new"]`. I should have? Don't know how.
=> Optional chaining '?.'

1-js/99-js-misc/04-reference-type/article.md
J'étais pas sûr de la traduction de "Reference type" donc je me suis basé sur cet article:
https://fr.wikipedia.org/wiki/Type_valeur_et_type_r%C3%A9f%C3%A9rence
=> Reference Type

9-regular-expressions/06-regexp-boundary/1-find-time-hh-mm/solution.md, 9-regular-expressions/06-regexp-boundary/1-find-time-hh-mm/task.md, 9-regular-expressions/06-regexp-boundary/article.md
Article and task translation to "Limite de mot : \b"
=> Word boundary: \b

9-regular-expressions/07-regexp-escaping/article.md
=> Escaping, special characters

9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/solution.md, 9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/task.md, 9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/solution.md, 9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/task.md, 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
reviewed with local engine,
add link to wikipedia for surrogate pair, as french translation is not obvious,
choose [unicode.org](https://www.unicode.org/terminology/term_en_fr.html#S) translation but it didn't match the unicode chapter translation "paire de substitution"
=> Sets and ranges [...]

9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/solution.md, 9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/task.md, 9-regular-expressions/10-regexp-greedy-and-lazy/3-find-html-comments/solution.md, 9-regular-expressions/10-regexp-greedy-and-lazy/3-find-html-comments/task.md, 9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/solution.md, 9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/task.md, 9-regular-expressions/10-regexp-greedy-and-lazy/article.md
The quotation was tricky, and hopefully I didn't let typos.
=> Greedy and lazy quantifiers

1-js/04-object-basics/02-object-copy/article.md
maintenant => maintenant
At the end, the conclusion was appearing as <pre>. It is a mismatched with ``` before. I think that I have recreated the well balanced text. Thanks for this excellent tutorial.
=> Update article.md - some basic corrections

9-regular-expressions/11-regexp-groups/01-test-mac/solution.md, 9-regular-expressions/11-regexp-groups/01-test-mac/task.md, 9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/solution.md, 9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/task.md, 9-regular-expressions/11-regexp-groups/03-find-decimal-numbers/solution.md, 9-regular-expressions/11-regexp-groups/03-find-decimal-numbers/task.md, 9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md, 9-regular-expressions/11-regexp-groups/04-parse-expression/task.md, 9-regular-expressions/11-regexp-groups/article.md
It's been a while but it's now ready
=> Capturing groups

2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md, 2-ui/1-document/04-searching-elements-dom/1-find-elements/table.html, 2-ui/1-document/04-searching-elements-dom/1-find-elements/task.md, 2-ui/1-document/04-searching-elements-dom/article.md
Traduction française de la page [Searching: getElement*, querySelector*](https://fr.javascript.info/%3C/div)
=> Searching: getElement*, querySelector*

1-js/02-first-steps/12-nullish-coalescing-operator/article.md
In the article `L'opérateur de coalescence des nuls '??'` the priority of the operators `??` and `||` was incorrect. This PR corrects that.
=> Fixed wrong priority of operators `??` and `||`

2-ui/99-ui-misc/03-event-loop/article.md
The code is written in english so [this console log](https://github.com/javascript-tutorial/fr.javascript.info/commit/f9293128225b2caac6c6830c078945e9c34ddcc8#diff-b43ffe11af05abaed45d48a22b3df851828b0c23a7395e56edae64841e2ba070R255) not print "promesse" but "promise"
=> chore: fix incorrect french translation

README.md
This commit updates the URL of the French JavaScript tutorial in the README.md file to point to the correct address: https://fr.javascript.info.
=> Update the URL of the French JavaScript tutorial in README.md

1-js/13-modules/01-modules-intro/article.md, 1-js/13-modules/02-import-export/article.md, 1-js/13-modules/index.md, 1-js/99-js-misc/01-proxy/article.md, 1-js/index.md
Corrige plusieurs traductions de 'Summary' en 'Résumé' dans les fichiers suivants :
- 1-js/13-modules/01-modules-intro/article.md
- 1-js/13-modules/02-import-export/article.md
- 1-js/99-js-misc/01-proxy/article.md
Corrige la traduction de 'language' en 'langage' dans le fichier suivant :
- 1-js/index.md
=> Corrige des traductions de 'Summary' et 'Language'

1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md, 1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md, 1-js/10-error-handling/1-try-catch/article.md, 1-js/10-error-handling/2-custom-errors/1-format-error/task.md, 1-js/10-error-handling/2-custom-errors/article.md
Apporte diverses corrections et améliorations mineures au chapitre "1-js/10-error-handling".
Dans la partie "Catch global", pour le texte du message d'avertissement "Spécifique à l'environnement", je ne suis pas sûr que ma correction soit optimale :
Original (anglais) : "The information from this section is not a part of the core JavaScript."
Original (français) : "Les informations de cette section ne font pas partie du code JavaScript principal."
Proposition : "Les informations de cette section ne font pas partie du JavaScript de base."
Est-ce que traduire "_core JavaScript_" par "_JavaScript de base_" vous semble correct ?
=> Apporte plusieurs corrections au chapitre 1.10 (Gestion des erreurs)

1-js/01-getting-started/1-intro/article.md, 1-js/01-getting-started/index.md, 1-js/02-first-steps/01-hello-world/article.md, 1-js/02-first-steps/05-types/article.md, 1-js/06-advanced-functions/03-closure/article.md, 1-js/11-async/02-promise-basics/article.md, 1-js/11-async/07-microtask-queue/article.md, 2-ui/1-document/04-searching-elements-dom/article.md, 2-ui/2-events/04-default-browser-action/article.md, 2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/task.md, 2-ui/3-event-details/7-keyboard-events/article.md, 3-frames-and-windows/01-popup-windows/article.md, 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md, 9-regular-expressions/09-regexp-quantifiers/article.md, 9-regular-expressions/11-regexp-groups/article.md, 9-regular-expressions/13-regexp-alternation/03-match-quoted-string/task.md, 9-regular-expressions/17-regexp-methods/article.md
Apporte diverses corrections globales à tout le tutoriel :
- Corrige le terme **_language_** en **_langage_** dans tout le tutoriel.
- Corrige aussi certaines mauvaises traductions de **_language_** en anglais en **_langue_** en français.
- Corrige certains termes **_Javascript_** en **_JavaScript_**.
- Quelques autres petites corrections de mise en forme.
=> Corrige le terme 'language' en 'langage'

9-regular-expressions/09-regexp-quantifiers/article.md
Solve the problem mentioned in #504 issue.
=> docs: fix typo, from 'zéro ou plus' -> 'zéro ou un'

1-js/05-data-types/04-array/article.md
Saw the problem for #501 issue
=> fix: Translate `Get last elements with `at`` paragraph in `1-js/05-data-types/04-array/article.md` file.
